# Generated by Django 2.2.13 on 2020-06-21 18:53

from django.db import migrations
import twitteruser.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', twitteruser.models.UserManager()),
            ],
        ),
    ]
